### ISSUE TITLE
2.1.16: Update-Branches

### ISSUE THREAD

**Issue by Ston3s** [StoneOffStones/plugin.video.xstream#63]
Hallo zusammen,

wir warten zwar noch auf das eine oder andere Feature welches noch eingebaut werden muss. Trotzdem    sollten wir uns so langsam eventuell schon Gedanken über das große Update in Richtung Master-Branch machen. 
Dazu ist es bei diesem Versionssprung noch einmal notwendig eigene Update-Braches zu erstellen um es Lynx187 so einfach wie nur möglich zu machen.
Dieses Issue soll es uns ermöglichen für alle Änderungen ein geeignetes Brach zu definieren.
Wenn dies erfolgt ist, kann man diese Plattform nutzen um sich bis zur finalen Bereitstellung entsprechend abzustimmen ;)

Benennung sollte allerdings eindeutig und logisch stattfinden.
Ich dachte daran, dass der erste Teil des Namens immer gleich ist damit man auch noch später weiß welche Funktion das Addon hatte.

Bitte vervollständigen!!!
### 1. update-autoupdate (PULL REQUEST + MERGED)
- Error Check in updateManager
- Update nur im Hauptmenü
- Aktuellen UpdateManager
- #8, #14, #15
### 3. update-hdfilme  (PULL REQUEST + MERGED)
- korrekte ViewTypes
- [HDFilme.tv] Filme regex error #60 
### 6. update-siteplugins (PULL REQUEST + MERGED)
- KinoLeak fix #55, #9 
- Cryptopy Abhängigkeit
- SE: Fix series only showing first page #35
- BurningSeries Random Feature #50 
- new Site-Icon for ddl.me
- Alphabetische Sortierung in Übersicht
- Gleiche Namensgebung der Site-Plugin
- bundesliga.py entfernen
- gstream entfernen
### 7. update-basics (PULL REQUEST)
- ~~Neuen UrlResolver integrieren~~
- ~~fix AutoPlay bug~~
- pluginDB Update #13 
- ~~Fixed download method #34 + #38 + #43~~
- ~~fix der Meta-Suche (Line88)~~
- ~~Anpassung des Logger verhaltene #48~~
- ~~Force disable the metahandler, until a valid apikey is available #53~~ 
- Update Readme+FAQ #51 
- Identische Sprachenbezeichnung in Settings wie bei Kodi
- Zuordnung einzelnen Einstellungen den GeneralArts von Kodi
- Zentraler Ordner für Einstellungen
- ~~Sprung auf 2.2.0 #24~~

**Comment by Ston3s** [comment]
Habe mal den ersten Beitrag entsprechend erweitert.
Hab ich alles wichtige drin, fehlt noch was.
Wenn nicht würde ich die Branches mal gleich erstellen.
Dann könnte man sich schon fleißig ans werk machen...

Feedback ist immer gut ;)

**Comment by ghost** [comment]
So ich habe das gestern für HDFilme.TV mal gemacht. Wollen wollen wir das zum Testen mal zum Master mergen oder wollen wir alles zusammen machen?

(Ich hätte noch ein commit was eine nicht genutzte Variable entfernt, soll ich das noch machen? Oder wollen wir die Branche dann noch mal neu machen? ^^)

**Comment by Ston3s** [comment]
👍👍👍
Warten und zusammen mergen. Also kannst den Commit noch ruhig einbringen!

Werde zur Übersichtlichkeit alles was erledigt in der Issue-Beschreibung durchstreichen.

**Comment by ghost** [comment]
Dann bekommt der arme Lynx187 aber am Tag x nen riesen Berg ^^

Weil wenn man den Pull jetzt startet. Wird er ja sogar automatisch ergänzt (falls sich bis zum merge noch Änderungen ergeben)

Ich bin dafür die branches sofern, sofern sie gefüllt wurden. Als Pull los zu jagen.

**Comment by ghost** [comment]
Und wie machen wir es nun? ^^

**Comment by Ston3s** [comment]
Mein Gedanke ist dabei, dass ich möglichst alle Änderungen sauber übergeben möchte. Wenn dann einige übergeben und angenommen sind und andere nicht was dann?

Irgendwann will man ja weiter machen und dafür ist es notwendig einen Kahlschlag zu machen und die Master-Version zu übernehmen. Könnte ich aber nicht weil manches übergeben und anderes wiederum nicht übergeben ist.

**Comment by Ston3s** [comment]
Gibt es sonst schon Fortschritte, wollte mich heute Nachmittag etwas damit beschäftigen und dann auch den Status aktualisieren.

**Comment by ghost** [comment]
Eben drum würde ich halt die Branches (wenn sie fertig sind) am liebste direkt zur Master schicken. Damit @Lynx187 sie in ruhe annehmen kann. Das halt ich für sinniger als zu warten bis alles gemacht wurde und dann einen Berg zu kommen lassen.

Ggf. werde eh ein paar Sachen nicht angenommen.

**Comment by Ston3s** [comment]
Da bin ich ja sowieso mal gespannt drauf!

Von mir aus können wir es machen aber ich habe es im Vorfeld kommuniziert. Die bestehende Nightly Branch wird erst durch die neue Master ersetzt wenn alle Update-Branches entsprechend gepushed sind...

**Comment by ghost** [comment]
Muss ja. Nur wir müssen langsam alles rüber bekommen. Denn die Änderungen in der Master bräuchten wir auch in der nightly (grade den SSL-Part)

HD-Filme habe ich mal rüber geschickt und DDL.me mache ich nachher.

Aber ansich finde ich das mit dem Branches spitze. Falls @Lynx187 noch etwas zu beanstanden hat muss ich nur nen commit machen und der Pull bleibt trotzdem bestehen. Bis alle zufrieden sind und der Merge durchgeht.

**Comment by sraedler** [comment]
Hab auch den Updatemanager als Pull Request bereit gestellt.

Sollte normalerweise so passen

**Comment by Ston3s** [comment]
Könnte mir jemand noch bei den beiden offenen Optionen in den Einstellungen zu dem Global Search an erster Stelle und dem zentralen Settings Ordner weiterhelfen.

War ja noch nicht drin und Lynx187 meinte er hätte nichts dagegen wenn es optional wäre...

**Comment by sraedler** [comment]
Meinst du ein Setting, dass man wählen kann ob es ein Settingsfolder gibt oder nicht?

**Comment by ghost** [comment]
Das gehört hier nich rein. Aber ich habe nen Bug mit dem Settings-Folder und zwar wenn mein nen neue Site auswählt trägt er die nicht direkt rein. Ich muss aus xStream raus und wieder rein damit die Liste neu aufgebaut wird.

**Comment by Ston3s** [comment]
Jo, Setting für Setting Folder und Setting für Global Search auf erster Position

**Comment by Ston3s** [comment]
War noch nicht an Rechner und konnte nicht schauen wie die PRs von euch erstellt wurden. Habt ihr die von mir erstellen Branches verwendet, hoffe hat alles von meiner Seite aus so gepasst

**Comment by ghost** [comment]
So habe meine Site-Addons rübergeschickt und HDFilme.tv ist schon drin. Bei den andern beiden muss ich nachher noch mal ran etwas aufräumen.

Könntest du mal nen Merge von der Hauptforke in die NIghtly machen? Grade die SSL Sachen könnte ggf. Leute stören wenn sie die Nighly benutzen.

**Comment by sraedler** [comment]
@Viper2k4 kannst du beschreiben wie du zu dem Bug im Settings-Folder kommst?

Ich hab es versucht, bei mir geht es. Es wird nämlich anschließend _oGui.updateDirectory()_ aufgerufen und dann ist die neue Seite da.

P.s. mach bitte einen Bug auf....

**Comment by Ston3s** [comment]
Werde heute Abend den letzten Stand vom
Master updaten.
Bitte um anschließende Unterstützung bei auftretenden Konflikten.

**Comment by Ston3s** [comment]
Eben gemerged und jetzt geht gar nichts mehr...

**Comment by ghost** [comment]
So Pulls sind gemerged (update-manager, ddl.me, animie-loads, gute-filme.to). Könnte man also auch wieder richtung nightly holen. Dann haben wir schon mal nen schöne Basis.

**Comment by sraedler** [comment]
ja "frischer" Beta und nightly wäre was...

und dann häufigere pull requests und update Branchen schließen

**Comment by Ston3s** [comment]
Wollte erst schließen wenn alles übergeben ist.
Leider bin aktuell ziemlich häufig dienstlich unterwegs und komme zu nichts!

Wie sieht es eigentlich um die fixes für die SitePlugins, die unter dem Branch "update-siteplugins" aufgezählt sind. Muss man da noch was übergeben oder hat Lynx187 schon alles in der Master?

**Comment by Ston3s** [comment]
Kann mir noch jemand mit den entsprechenden Einstellungen für die "Central Settings" Sache und die Position der Globalen Suche weiterhelfen?

Sonst bin ich mir da ziemlich sicher das Lynx187 das nicht übernehmen wird. Hatte er in den eigentlichen Issues so kommuniziert.

**Comment by ghost** [comment]
**BurningSeries fix (HTTPS bzw. API)**
 **KinoLeak fix #55, #9** (Hier gab es keine Changes an der Kino-Leak-Datei, nur das unbennen was ich mal außen vorlasse)
 SE: Fix series only showing first page #35
BurningSeries Random Feature #50
 **fix GlobalSearch**

Bei den Dickgeschrieben Sachen weiß ich das sie gefixt sind.

**Comment by sraedler** [comment]
random kann getestet werden #50

**Comment by Ston3s** [comment]
Ok, soeben wurde die Master in meinem Fork aktualisiert und alle von Lynx187 angenommen Pos ebenfalls in die Nightly eingebaut.

Next Step wäre die update-siteplugins zu pushen...

**Comment by Ston3s** [comment]
Also habe jetzt erstmal "update-siteplugins" soweit angepasst.
Vielleicht könnt ihr mal einen Blick drauf werfen ob alles soweit ok ist.
Sage schon mal danke!

**Comment by Ston3s** [comment]
PR für obiges Thema wurde eingereicht.

Wie siehts mit den den Anpassungen in den Optionen aus, würde mich über ein kurzes Feedback freuen.
Gibt es bei den Punkten für update-Basics was zu berücksichtigen?!

**Comment by Ston3s** [comment]
Lynx meinte das in Update-Basic noch einige ident errors bei BS und SE.
Habe allerdings nur die Veränderungen von "euch"  in der Nightly eingepflegt.

**Comment by Ston3s** [comment]
Könntet ihr da mal vielleicht bitte einen Blick drauf werfen?

**Comment by ghost** [comment]
Also bei BS ist das komplett bei `randomEpisode`,`randomSeason`,`randomSerie` und `showRandom` und vereinzelt auch mitten drin. Scheint wohl mit #50 rein gekommen sein.

Und bei SW in Zeile 153 und 154. Scheint #34 gewesen zu sein.

Habe grade kein Kodi zur Hand zum Testen. Aber im Notepad++ (Ansicht => Nicht druckbare Zeichen => Leerzeichen und Tabulatoren) sieht man das dann ganz gut. Weil Pyton kein Tab mag zum einrücken.

**Comment by ghost** [comment]
So ich glaube ich habe alle erwischt. Aber @sraedler bitte mal drüber gucken ob es jetzt passt/läuft

**Comment by sraedler** [comment]
Ich hab es getestet, es funktioniert. Ich weiß nicht warum das passiert ist, bei mir in Pycharm sieht beides gleich aus (auch beim vergleichen der commits). Es geht aber.

Jedoch besteht ein Bug, der mir zuvor nicht aufgefallen ist. Er ist bezüglich utf-8, gleich wie #64.

Er kann so er zeugt werden: Zufalls Episode wählen und die Serie "100 Code" wählen. Anschließend die Staffel. Ab und an kommt nun ein UnicodeEncodeError.

Werde es gleich fixen, war ein blöder kleiner bug

**Comment by ghost** [comment]
Donno ich habe deine Version ins Notepad++ kopiert und dort sieht man das sehr gut (so fern die Option eingestellt ist). Aber Pycharm muss ich mir mal angucken. Sieht echt gut aus. Wobei ich gesehen habe das VisualStudio wohl auch Pyton support hat, das wollte ich mir die tage mal ansehen.

Aber wir weichen ab :)

**Comment by ghost** [comment]
Du solltest btw. auch noch folgendes beim Title berücksichtigen:

```
if episode['german']:
     title += episode['german'].encode('utf-8')
else:
     title += episode['english'].encode('utf-8')
```

so wird es eigentlich überall in BS gemacht. Nur bei randomEpisode fehlt das noch.

**Comment by Ston3s** [comment]
Danke fürs reinarbeiten!!!

**Comment by ghost** [comment]
Ich habe das mit dem Fallback mal eingebaut. Sprich wenn kein Deutsch Title vorhanden ist wird der englische benutzt.

**Comment by Ston3s** [comment]
Top, hoffentlich wars das mit "update-siteplugins".
Ich wollte jetzt gerne bis zum WE die "updates-basics" soweit auf Stand bringen.
Gibt es dort was wichtiges berücksichtigen?
Kann man noch mit den Anpassung in den Optionen zwecks "Central Options" und "GlobalSrearch at first" rechnen?

**Comment by StoneOffStones** [comment]
rechnen ;)

**Comment by sraedler** [comment]
das global search find ich sinnvoll, das Central folder eigentlich nicht...

wenn ich Zeit finde mach ich es heute

**Comment by Ston3s** [comment]
Danke, kann man ja dann in den Einstellungen selber entscheiden ;)

**Comment by sraedler** [comment]
So jetzt hast deine Settings ;)
c69833f

Evtl. müssen die Texte noch für Englisch und Deutsch geändert werden, mir fiel nämlich nichts besseres ein.

**Comment by Ston3s** [comment]
Ok super!

Mir ist aufgefallen das die Änderung in der Nightly und nicht in der Update-Branch ist. Werde ich dann später übertragen und hoffe das die xstream.py identisch/ähnlich ist, sodass  keine Fehler dadurch übergeben werden.

**Comment by Ston3s** [comment]
Muss ich eigentlich was berücksichtigen wenn ich die Position der Einstellungen verändern will?

**Comment by ghost** [comment]
Direkt nicht. Aber die Frage ist eher wieso? :)

**Comment by Lynx187** [comment]
Das einzige was man beachten sollte ist, dass die `enable` Tags sich relativ von der Position auf andere Settings beziehen. Mehr Infos, Kodi Wiki.
Das bringt mich zur Frage wozu sollen die enable Tags in c69833f gut sein?
PS: GlobalSearch kann auch fix als erstes stehen da muss man nicht noch extra eine Option einführen.

**Comment by Ston3s** [comment]
Man könnte es ja die Option GlobalSearch at First standardmäßig aktivieren. Finde jedoch die Möglichkeit die Suche vor den Einstellungen zu platzieren durchaus interessant. Ich z.B. Nutze diese globale Suche für alle Seiten extrem selten.

Muss ich bei einer überarbeiteten Sortierung der Einstellungen nur die Position anpassen oder auch die jeweiligen Labels?
Oder wird über die Labels die Verknüpfung zur eigentlichen Funktion hergestellt?
Bin erst morgen Abend in der Lage in wie Kodi Wiki zu schauen, wollte vorab aber schon mal nachfragen...

**Comment by ghost** [comment]
Was muss denn hier noch gemacht werden? Wäre nämlich schön wenn wir die Nightly wieder auf Stand der Master bekommen.

btw was haltet ihr eigentlich von folgenden Plan für den Updater:

Master => quasi das was in der Repro ist
Beta => git-stand von Lynx1781
Nightly => diese Repro hier

Dann sollten wir für unsere Änderungen immer Branches anlegen und diese nach Lynx1781 pullen. Die Nightly kann sich die Änderungen der Brances ja immer direkt holen (kann man das Automatisieren?). Das heißt wir haben keine Direkte Entwicklung in der Nightly. 

Aber so bleibt der Code-Verlauf von Nightly => Beta => Master wengistens konstant soweit.

**Comment by Ston3s** [comment]
Update-Basic müsste noch auf Stand gebracht werden bevor der PR erzeugt werden kann. Wollte ich eigentlich schon am Wochenende angehen aber gerade komme ich zeitlich nicht dazu...

**Comment by Lynx187** [comment]
Also nur zu Info ich werde spätestens am 30.4. den Stand und damit eine neue Version ins xStreamRepo übertragen.
Was momentan noch unter Update Basics steht:
- [x]  Neuen UrlResolver integrieren -> eine Lösung bereits umgesetzt 
- [x]     fix AutoPlay bug -> k.A. trat in der master nicht auf
- [ ]     pluginDB Update #13
- [x]     Fixed download method #34 + #38 + #43 -> sollte enhalten sein
- [x]     fix der Meta-Suche (Line88) -> eine Lösung bereits umgesetzt
- [x]     Anpassung des Logger verhaltene #48 -> eine Lösung ist bereits umgesetzt
- [x]     Force disable the metahandler, until a valid apikey is available #53 -> wird nicht passieren siehe Kommentar
- [x]     Update Readme+FAQ #51
- [x]     Identische Sprachenbezeichnung in Settings wie bei Kodi
- [x]     Zuordnung einzelnen Einstellungen den GeneralArts von Kodi
- [x]     Zentraler Ordner für Einstellungen
- [x]     Sprung auf 2.2.0 #24 -> ist vorgesehen

Alles was noch offen ist eher optional. Wenns es noch rechtzeitig kommt ok, wenn nicht dann später, da für die Funktion irrelevant.

**Comment by sraedler** [comment]
@Lynx187 kannst du "pluginDB Update #13" etwas beschreiben, was du da gerne hättest?

das "fix AutoPlay bug" ist bei dir auch nicht vorhanden, das war ein Mergefehler

**Comment by Ston3s** [comment]
Ok verstanden, versuche mich heute oder morgen dran zusetzen.

Was sagst du viper2k4's Idee deine Master als Beta zu verwenden?!
Ich habe auch bereits über etwas ähnliches nachgedacht jedoch müsste dann wieder obwohl die AutoUpdate Funktion vorhanden ist auf zwei wegen bereitgestellt/gearbeitet werden. Theoretisch brauch in der Repo nur eine Version mit UpdateManager verfügbar sein. Danach müsste xStream in der Repo nicht mal mehr aktualisiert werden da die Updates dann über GitHub bezogen werden würden.

Auf der anderen Seite stimmt es, dass die Master nicht nur reine final Stände aufweist da in dieser auch regelmäßig gearbeitet wird. So gesehen entspricht es durchaus eher einer Beta.

Zu guter letzt stellt sich dann die Frage sind die Tags für die Betas dann noch überhaupt erforderlich?
Vielleicht könnte man diese Markierung dann dafür nutzen um die Finalen Stände kenntlich zu machen damit diese über die AutoUpdate Funktion bezogen werden können.
Weiß auch nicht ob die Nightly wie von Viper geschrieben automatisch aktualisiert werden kann?!

Unter Berücksichtigung des oben geschriebenen wäre für mich die sinnigste Variante wie folgt...

Nightly:
weiterhin nightly-branch, Bereitstellung erfolgt in kleineren Steps

Beta:
master-branch von Lynx187 wird durch Nightly und andere Mitwirkende mit PR's versorgt

Master:
neue Stände mit stable Status würden über Tags definiert und könnten so AutoUpdate bezogen werden

**Comment by Lynx187** [comment]
@sraedler  es  behebt nicht das eigentliche Problem aus dem Issue und die Aussage der Meldung sollte min.1 SitePlugin sein nicht mehr als 1.

AutoUpdate:
Stimmt nur so lange sich an den Dependencies nichts ändert.
Der Rest stimmt so und da bei der Master ja ohnehin auf geänderte Versionsnummern geachtet wird kann man das natürlich (Beta und Master in einem Branch) auch darüber lösen oder über Tags oder über Releases wie man mag.

**Comment by Ston3s** [comment]
Und wie magst du das?
Für mich stellt soweit kein Problem dar, müsste nur abgestimmt und von allen akzeptiert werden.

Dann könnte man auch, falls jetzt anders abgestimmt wird, noch die Update-Bezugsquellen vor ausrollen der nächste Final angepasst werden

**Comment by Ston3s** [comment]
Die erwähnten Releases werden meines Wissens beim erstellen von Tags automatisch erzeugt ;)

**Comment by sraedler** [comment]
Mir ist das eigentlich egal, welcher Branch für was genutzt wird. Bin mir eh nicht sicher ob wirklich drei Unterschiedliche benötigt werden oder ob es reicht, wenn ein Stable und ein "Entwickler" Modus bereitgestellt wird.

**Comment by Ston3s** [comment]
Muss nur definiert und gelebt werden...

**Comment by Ston3s** [comment]
Habe jetzt alle Änderungen bis auf "pluginDB Update" und eine entsprechende Anpassung der Bezugsquellen der AutoUpdate Funktion in Update-Basics integriert.
Würde gerne PR erstellen!

Wenn die beiden Punkte noch nachgereicht werden würde ich mich freuen.
Solang das PR noch nicht von Lynx angenommen wurde können zusätzliche Commits dem PR hinzugefügt werden. Ansonsten kann eine zusätzliche Update-Branch erstellt werden ;)

**Comment by Ston3s** [comment]
Mir ist noch eine Sache zu der zur jeweiligen Branch-Zuweisung eingefallen. 
Wie macht man es dann mit der Addon/Benennung wenn die Master von Lynx zur Beta wird. 
Aktuell ist gleich auf den ersten Blick zu sehen dass es sich um xStream (Nightly) oder xStream (Beta) handelt.
Das würde bei der oben vorgeschlagenen Variante stören!

**Comment by Ston3s** [comment]
Mir ist eben noch aufgefallen das in den Settings einige Optionen groß andere wiederum klein geschrieben sind.

Kann man das noch schnell anpassen und wenn ja wo genau?!
Danke für die Hilfe...

**Comment by Ston3s** [comment]
Der letzte PR aus dieser Issue wurde jetzt auch übernommen. Stellt sich nur noch die Frage wie die n Zukunft bereitgestellt wird.

Sollen die Finalen oder die Beta Versionen getagt werden, wo und durch wen geschieht dies?
Außerdem müsste der Code am besten vor 2.2.0 angepasst werden, falls was anders laufen soll...

**Comment by ghost** [comment]
Wie gesagt ich bin für:
- Nightly zieht sich immer die änderungen aus den ganzen Branches zusammen
- Beta ist der Branche von Lynx187 
- Master ist quasi die Version aus der Repro

So ist die Nightly wirklich das Zeug was was wir direkt entwickeln. Die Beta ist quasi wirklich getestet. Naja und Master ist halt Master.

(Wenn wir das wirklich so machen wollen müssten wir btw. fix den Updater noch anpassen bis zur Verteilung von 2.2.0)

**Comment by Ston3s** [comment]
Wenn man dann gar nicht mehr in der Nightly entwickeln dann kann man sich diese auch sparen. Den genau dafür wurde diese ja eigentlich benötigt bzw. gefordert.
Dann würde man ja an verschiedensten Fronten entwickeln mühselig alles händisch in der Nighly packen und diese würde wiederrum keinen tatsächlichen Mehrwert für die Entwicklung haben.

Ich fand den Ansatz aus der anderen Issue zum Thema ganz gut.

Entwickelt wird in der Nightly aber in kleineren Steps und eins nach dem anderen. (Wenn Themen erst im folgenden Milestone sein sollen kann man ja trotzdem schon für sich beginnen und testen aber den Commit halt im nächsten Step tätigen.

Das einzige was in meinen Augen sinnvoll ist das die Master von Lynx zur Beta wird und das Repo bzw. die Tags zur stable (wobei Tag im
Bezug auf AutoUpdate sinniger wäre)

**Comment by Ston3s** [comment]
Hatte noch das rebase vor der Übermittlung an die Beta-Branch von Lynx vergessen. Damit werden alle Veränderungen in einem Commit komprimiert. Deshalb müssen es auch zwangsläufige kleine Steps sein.(Übersichtlichkeit)

**Comment by ghost** [comment]
Ohne Branches lässt sich aber beil Pull-Request nichts trennen. Sagen wir ich Arbeite an HD-Filme.py und sraedler baut an was anders. Jetzt bin ich fertig und würde gern nen Pull machen. Dann sind die Änderungn von sraedler da aber auch mit drin. Und das stört dann.

Es wäre aber ohne Probleme möglich von der Branche von mir und sraedlers branches die merges in die nightly zu machen. Damit hat jemand der die Nightly bezieht trotzdem direkt die neusten Änderungen und trotzdem getrennte Entwicklungsbereiche.

**Comment by Ston3s** [comment]
Deshalb auch Entwicklung in kleinen Steps von voneinander unabhängigen Themenbereichen und der Vermerk das ja trotzdem von den einzelnen an späteren Änderungen gearbeitet werden kann. Es darf halt nur kein Commit vom jeweiligen gepushed werden damit sich die Themen nicht vermischen.

Ihr seid selber schuld das ich so argumentiere :)
Ich denke da nur an die Aussage das PullRequests nur stören und man so nicht recht vorankommt.
Jetzt müsste man allerdings zwei PRs anstatt einem machen. Einmal in die Nightly und einmal in die Master von Lynx

**Comment by Ston3s** [comment]
Mir sollst wurscht sein der Schwenk in der Argumentation hat mich nur sehr gewundert.

Dazu gab es schon genug Fürs und Widers.
Lynx bitte sag was dazu und so wirds dann einfach gemacht...

**Comment by Lynx187** [comment]
Branches für zusammengehörige Dinge und dann PR. Der Übersichlichkeit wegen.
master als Beta und tagged oder Repo als Final, ok im master landet ja doch noch mal was nicht so astreines.

"Nightly" halte ich persönlich nicht so viel von und ja das wäre extra Aufwand. Kann man evtl mit einem Script automatisieren wenn es einem wichtig ist.

**Comment by Ston3s** [comment]
Dann ist die Nightly allerdings komplett ohne Mehrwert, aber wie ihr wollt.
Wer stellt dann die Tags in der Master her?
Wir haben ja keine Berechtigungen...

**Comment by sraedler** [comment]
so, jetzt ist ja alles gemerged, sollen wir nun den Master von Lynx wieder als Basis nehmen? also eine Art reset, dass wirklich die gleiche Basis da ist...

**Comment by Ston3s** [comment]
Bereits geschehen. Habe da auch schon die eingereichten Verbesserungen an den Settings einfließen lassen.
